services:
  app:
    build: .
    container_name: goquick_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: goquick_db
    restart: always
    environment: 
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: goquickdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
